// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:convert' show base64, utf8;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

String _resolveKey(String b64) => utf8.decode(base64.decode(b64));

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _resolveKey('QUl6YVN5QzR1RS1Wa21nQ1Z5WXBTMFJXUlRWazUtWDNfZFloQ0lr'),
    appId: '1:1067379970689:web:4142d4e974d8e65d86b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    authDomain: 'exemplary-datum-397601.firebaseapp.com',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
    measurementId: 'G-YZRC631MTC',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _resolveKey('QUl6YVN5RFR0MFUtOExhYWdQc2hvMU04UWY0QnIzY01BUWdJVW1R'),
    appId: '1:1067379970689:android:8434b203f44e23af86b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
  );
  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _resolveKey('QUl6YVN5RFRwOEc2SXBqdUw0cVpjVHNoXzN2ajlmTlRYeTJGUGdn'),
    appId: '1:1067379970689:ios:00cba5071beb2c5886b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
    iosBundleId: 'mx.edu.tecnm.colima.sinait',
  );
  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: _resolveKey('QUl6YVN5RFRwOEc2SXBqdUw0cVpjVHNoXzN2ajlmTlRYeTJGUGdn'),
    appId: '1:1067379970689:ios:00cba5071beb2c5886b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
    iosBundleId: 'mx.edu.tecnm.colima.sinait',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: _resolveKey('QUl6YVN5QzR1RS1Wa21nQ1Z5WXBTMFJXUlRWazUtWDNfZFloQ0lr'),
    appId: '1:1067379970689:web:913862ac986b84d186b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    authDomain: 'exemplary-datum-397601.firebaseapp.com',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
    measurementId: 'G-F42G8ZN72F',
  );
}
