// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4uE-VkmgCVyYpS0RWRTVk5-X3_dYhCIk',
    appId: '1:1067379970689:web:4142d4e974d8e65d86b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    authDomain: 'exemplary-datum-397601.firebaseapp.com',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
    measurementId: 'G-YZRC631MTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTt0U-8LaagPsho1M8Qf4Br3cMAQgIUmQ',
    appId: '1:1067379970689:android:8434b203f44e23af86b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTp8G6IpjuL4qZcTsh_3vj9fNTXy2FPgg',
    appId: '1:1067379970689:ios:00cba5071beb2c5886b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
    iosBundleId: 'mx.edu.tecnm.colima.sinait',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTp8G6IpjuL4qZcTsh_3vj9fNTXy2FPgg',
    appId: '1:1067379970689:ios:00cba5071beb2c5886b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
    iosBundleId: 'mx.edu.tecnm.colima.sinait',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4uE-VkmgCVyYpS0RWRTVk5-X3_dYhCIk',
    appId: '1:1067379970689:web:913862ac986b84d186b380',
    messagingSenderId: '1067379970689',
    projectId: 'exemplary-datum-397601',
    authDomain: 'exemplary-datum-397601.firebaseapp.com',
    storageBucket: 'exemplary-datum-397601.firebasestorage.app',
    measurementId: 'G-F42G8ZN72F',
  );
}
