// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrz7CHooTTDdLj4Qd4BQwts2424Vef0fY',
    appId: '1:487588933269:web:3fae77563cd6c1bed4f59c',
    messagingSenderId: '487588933269',
    projectId: 'sinait-colima',
    authDomain: 'sinait-colima.firebaseapp.com',
    storageBucket: 'sinait-colima.firebasestorage.app',
    measurementId: 'G-FE28V884KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB583W_VrAXt0_I6N66DaRAIpnUodc-FGw',
    appId: '1:487588933269:android:a0caa6cbf409f30dd4f59c',
    messagingSenderId: '487588933269',
    projectId: 'sinait-colima',
    storageBucket: 'sinait-colima.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfnApig74rGctljhDs6cve9o3jQgllfVI',
    appId: '1:487588933269:ios:cdf3ffc633c66c0ad4f59c',
    messagingSenderId: '487588933269',
    projectId: 'sinait-colima',
    storageBucket: 'sinait-colima.firebasestorage.app',
    iosBundleId: 'mx.edu.tecnm.colima.sinait',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfnApig74rGctljhDs6cve9o3jQgllfVI',
    appId: '1:487588933269:ios:cdf3ffc633c66c0ad4f59c',
    messagingSenderId: '487588933269',
    projectId: 'sinait-colima',
    storageBucket: 'sinait-colima.firebasestorage.app',
    iosBundleId: 'mx.edu.tecnm.colima.sinait',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrz7CHooTTDdLj4Qd4BQwts2424Vef0fY',
    appId: '1:487588933269:web:c8f0e3f05f3a6f17d4f59c',
    messagingSenderId: '487588933269',
    projectId: 'sinait-colima',
    authDomain: 'sinait-colima.firebaseapp.com',
    storageBucket: 'sinait-colima.firebasestorage.app',
    measurementId: 'G-6J8RWTZZJM',
  );
}
